// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rle_length
size_t rle_length(List rle);
RcppExport SEXP _rleops_rle_length(SEXP rleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_length(rle));
    return rcpp_result_gen;
END_RCPP
}
// rle_sum
double rle_sum(List rle, bool na_rm);
RcppExport SEXP _rleops_rle_sum(SEXP rleSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_sum(rle, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// rle_mean
double rle_mean(List rle, bool na_rm);
RcppExport SEXP _rleops_rle_mean(SEXP rleSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_mean(rle, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// rle_add
List rle_add(List rle_a, List rle_b, bool recycle);
RcppExport SEXP _rleops_rle_add(SEXP rle_aSEXP, SEXP rle_bSEXP, SEXP recycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    Rcpp::traits::input_parameter< bool >::type recycle(recycleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_add(rle_a, rle_b, recycle));
    return rcpp_result_gen;
END_RCPP
}
// rle_substract
List rle_substract(List rle_a, List rle_b, bool recycle);
RcppExport SEXP _rleops_rle_substract(SEXP rle_aSEXP, SEXP rle_bSEXP, SEXP recycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    Rcpp::traits::input_parameter< bool >::type recycle(recycleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_substract(rle_a, rle_b, recycle));
    return rcpp_result_gen;
END_RCPP
}
// rle_multiply
List rle_multiply(List rle_a, List rle_b, bool recycle);
RcppExport SEXP _rleops_rle_multiply(SEXP rle_aSEXP, SEXP rle_bSEXP, SEXP recycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    Rcpp::traits::input_parameter< bool >::type recycle(recycleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_multiply(rle_a, rle_b, recycle));
    return rcpp_result_gen;
END_RCPP
}
// rle_divide
List rle_divide(List rle_a, List rle_b, bool recycle);
RcppExport SEXP _rleops_rle_divide(SEXP rle_aSEXP, SEXP rle_bSEXP, SEXP recycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    Rcpp::traits::input_parameter< bool >::type recycle(recycleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_divide(rle_a, rle_b, recycle));
    return rcpp_result_gen;
END_RCPP
}
// rle_eq
List rle_eq(List rle_a, List rle_b, bool recycle);
RcppExport SEXP _rleops_rle_eq(SEXP rle_aSEXP, SEXP rle_bSEXP, SEXP recycleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    Rcpp::traits::input_parameter< bool >::type recycle(recycleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_eq(rle_a, rle_b, recycle));
    return rcpp_result_gen;
END_RCPP
}
// rle_compact
List rle_compact(List rle);
RcppExport SEXP _rleops_rle_compact(SEXP rleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_compact(rle));
    return rcpp_result_gen;
END_RCPP
}
// rle_value_counts
List rle_value_counts(List rle);
RcppExport SEXP _rleops_rle_value_counts(SEXP rleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_value_counts(rle));
    return rcpp_result_gen;
END_RCPP
}
// rle_filter
List rle_filter(List rle_data, List rle_mask);
RcppExport SEXP _rleops_rle_filter(SEXP rle_dataSEXP, SEXP rle_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_data(rle_dataSEXP);
    Rcpp::traits::input_parameter< List >::type rle_mask(rle_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_filter(rle_data, rle_mask));
    return rcpp_result_gen;
END_RCPP
}
// rle_slice
List rle_slice(List rle, size_t start, size_t end);
RcppExport SEXP _rleops_rle_slice(SEXP rleSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    Rcpp::traits::input_parameter< size_t >::type start(startSEXP);
    Rcpp::traits::input_parameter< size_t >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_slice(rle, start, end));
    return rcpp_result_gen;
END_RCPP
}
// rle_which
IntegerVector rle_which(List rle);
RcppExport SEXP _rleops_rle_which(SEXP rleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_which(rle));
    return rcpp_result_gen;
END_RCPP
}
// rle_cummax
List rle_cummax(List rle);
RcppExport SEXP _rleops_rle_cummax(SEXP rleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_cummax(rle));
    return rcpp_result_gen;
END_RCPP
}
// rle_cummin
List rle_cummin(List rle);
RcppExport SEXP _rleops_rle_cummin(SEXP rleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle(rleSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_cummin(rle));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rleops_rle_length", (DL_FUNC) &_rleops_rle_length, 1},
    {"_rleops_rle_sum", (DL_FUNC) &_rleops_rle_sum, 2},
    {"_rleops_rle_mean", (DL_FUNC) &_rleops_rle_mean, 2},
    {"_rleops_rle_add", (DL_FUNC) &_rleops_rle_add, 3},
    {"_rleops_rle_substract", (DL_FUNC) &_rleops_rle_substract, 3},
    {"_rleops_rle_multiply", (DL_FUNC) &_rleops_rle_multiply, 3},
    {"_rleops_rle_divide", (DL_FUNC) &_rleops_rle_divide, 3},
    {"_rleops_rle_eq", (DL_FUNC) &_rleops_rle_eq, 3},
    {"_rleops_rle_compact", (DL_FUNC) &_rleops_rle_compact, 1},
    {"_rleops_rle_value_counts", (DL_FUNC) &_rleops_rle_value_counts, 1},
    {"_rleops_rle_filter", (DL_FUNC) &_rleops_rle_filter, 2},
    {"_rleops_rle_slice", (DL_FUNC) &_rleops_rle_slice, 3},
    {"_rleops_rle_which", (DL_FUNC) &_rleops_rle_which, 1},
    {"_rleops_rle_cummax", (DL_FUNC) &_rleops_rle_cummax, 1},
    {"_rleops_rle_cummin", (DL_FUNC) &_rleops_rle_cummin, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rleops(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
