// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// add_two
NumericVector add_two(NumericVector x);
RcppExport SEXP _rleops_add_two(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(add_two(x));
    return rcpp_result_gen;
END_RCPP
}
// rle_add
List rle_add(List rle_a, List rle_b);
RcppExport SEXP _rleops_rle_add(SEXP rle_aSEXP, SEXP rle_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_add(rle_a, rle_b));
    return rcpp_result_gen;
END_RCPP
}
// rle_multiply
List rle_multiply(List rle_a, List rle_b);
RcppExport SEXP _rleops_rle_multiply(SEXP rle_aSEXP, SEXP rle_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rle_a(rle_aSEXP);
    Rcpp::traits::input_parameter< List >::type rle_b(rle_bSEXP);
    rcpp_result_gen = Rcpp::wrap(rle_multiply(rle_a, rle_b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rleops_add_two", (DL_FUNC) &_rleops_add_two, 1},
    {"_rleops_rle_add", (DL_FUNC) &_rleops_rle_add, 2},
    {"_rleops_rle_multiply", (DL_FUNC) &_rleops_rle_multiply, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rleops(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
