# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#' 
#' A simple function to test Rcpp setup.
#' @param x A numeric vector
#' @export
add_two <- function(x) {
    .Call(`_rleops_add_two`, x)
}

#' Add two rle objects, element-wise
#'
#' @param rle_a An R rle list object
#' @param rle_b An R rle list object
#' @return An R rle list object containing the sum
#' @export
rle_add <- function(rle_a, rle_b) {
    .Call(`_rleops_rle_add`, rle_a, rle_b)
}

#' Multiply two rle objects, element-wise
#'
#' @param rle_a An R rle list object
#' @param rle_b An R rle list object
#' @return An R rle list object containing the product
#' @export
rle_multiply <- function(rle_a, rle_b) {
    .Call(`_rleops_rle_multiply`, rle_a, rle_b)
}

