# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#' 
#' A simple function to test Rcpp setup.
#' @param x A numeric vector
#' @export
add_two <- function(x) {
    .Call(`_rleops_add_two`, x)
}

